address: "#804, 24th Main Road,<br>&nbsp;&nbsp;&nbsp;&nbsp;12th Cross, JP Ngar Phase 2,<br>&nbsp;&nbsp;&nbsp; Bangalore - 78"
email: aradhana.interiors16@gmail.com
phone-1: +91-8618656767
phone-2: +91-9964599493
facebook:


destination: public

exclude:
    - New folder
    - public